INSERT INTO "Offers"
(
    "Id",
    "StoreId",
    "Title",
    "Slug",
    "OfferType",
    "ShortDescription",
    "Description",
    "TermsAndConditions",
    "ImageUrl",
    "CashbackType",
    "CashbackValue",
    "CashbackText",
    "CouponCode",
    "DestinationUrl",
    "StartAt",
    "EndAt",
    "IsFeatured",
    "Priority",
    "IsActive",
    "CreatedAt",
    "UpdatedAt"
)
VALUES
(
    'dddddddd-dddd-dddd-dddd-dddddddddddd',
    'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    'Up to 10% Cashback on Myntra',
    'myntra-up-to-10-percent-cashback',
    1,
    'Earn cashback when shopping on Myntra.',
    'Shop eligible fashion and lifestyle products on Myntra.',
    'Cashback is subject to tracking and eligibility rules.',
    '/media/offers/myntra-cashback.png',
    3,
    NULL,
    'Up to 10% Cashback',
    NULL,
    'https://www.myntra.com',
    CURRENT_TIMESTAMP - INTERVAL '1 day',
    CURRENT_TIMESTAMP + INTERVAL '30 days',
    TRUE,
    1,
    TRUE,
    CURRENT_TIMESTAMP,
    NULL
),
(
    'eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee',
    'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
    'Up to 7% Cashback on Flipkart',
    'flipkart-up-to-7-percent-cashback',
    1,
    'Earn cashback on eligible Flipkart purchases.',
    'Shop electronics, fashion and household products on Flipkart.',
    'Cashback rates may vary by product category.',
    '/media/offers/flipkart-cashback.png',
    3,
    NULL,
    'Up to 7% Cashback',
    NULL,
    'https://www.flipkart.com',
    CURRENT_TIMESTAMP - INTERVAL '1 day',
    CURRENT_TIMESTAMP + INTERVAL '30 days',
    TRUE,
    2,
    TRUE,
    CURRENT_TIMESTAMP,
    NULL
),
(
    'ffffffff-ffff-ffff-ffff-ffffffffffff',
    'cccccccc-cccc-cccc-cccc-cccccccccccc',
    'Flat ₹500 Cashback on Travel Booking',
    'makemytrip-flat-500-cashback',
    1,
    'Get flat cashback on eligible travel bookings.',
    'Book eligible flights, hotels or holiday packages.',
    'Minimum booking value and eligibility conditions may apply.',
    '/media/offers/makemytrip-cashback.png',
    2,
    500.00,
    'Flat ₹500 Cashback',
    NULL,
    'https://www.makemytrip.com',
    CURRENT_TIMESTAMP - INTERVAL '1 day',
    CURRENT_TIMESTAMP + INTERVAL '30 days',
    FALSE,
    3,
    TRUE,
    CURRENT_TIMESTAMP,
    NULL
)
ON CONFLICT ("Slug") DO NOTHING;